### ISSUE TITLE
TreeTwerk optimization

### ISSUE THREAD

**Issue by NotMyFault** [BentoBoxWorld/TwerkingForTrees#12]
#### Describe the bug

I'm not running into a bug, just into an optimization issue:
![](https://i.imgur.com/JNPKNmV.png)    
The named event is pretty heavy, considering it loads chunks sync to grows the trees.
It would be a charm if the event could be optimized/removed. I'm not sure if loading chunks sync is mandatory to grow trees.

#### Steps to reproduce the behavior

Not relevant

#### Expected behavior

Optimization of the named events.

##### BentoBox Version (Mandatory)

![](https://i.imgur.com/InpnPVK.png)

**Comment by tastybento** [comment]
Chunks have to be loaded to grow a tree but they should already be loaded unless the chunk is far away from a player. What are your island sizes and view distance?

I recently made a change that disabled twerking in the nether and end, so that should help. See release 1.2.0.

Also, there's a feature request to only allow twerking in a (small) radius around the player. That may help too.

**Comment by NotMyFault** [comment]
Island boundaries are 100x100 and view distance is 4.

**Comment by tastybento** [comment]
Okay.  I've made chunk loading when growing trees async. Please try 1.2.1 from the CI server.

**Comment by NotMyFault** [comment]
Aight, I'll give it a try and report back later

**Comment by NotMyFault** [comment]
Yup, that helped. Ty
