### ISSUE TITLE
Twerking permissions

### ISSUE THREAD

**Issue by FesterHead** [BentoBoxWorld/TwerkingForTrees#18]
User story:
As a server administrator, I want the ability to assign twerking permissions to users so that I can have control over which players can grow trees faster.

For maximum flexibility, I imagine the permissions would be based on tree-type such as:
* twerkingfortrees.oak
* twerkingfortrees.spruce
* twerkingfortrees.*

**Comment by tastybento** [comment]
I added `[gamemode].twerkingfortrees` permission. It's not straightforward to differentiate by sapling type because there's no particular relationship kept between twerkers (who can actually be numerous players in range who have the perm) and the ultimate tree growth. i.e., I don't try to monitor who is twerking and follow it all the way down the line. To do that would be a lot more complex to get this feature. So, for now, perfect being the enemy of the good and all that, here's just the overall permission!

**Comment by FesterHead** [comment]
Works for me!

**Comment by FesterHead** [comment]
Permission works well.  Most excellent.  Thank you!
