### ISSUE TITLE
Configurable radius for the "faster growth" effect

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/TwerkingForTrees#5]
#### Is your feature request related to a problem?

There is currently no way for server owners to specify how far the twerking effect reaches saplings.

#### Describe the solution you'd like us to implement.

A config option to set the radius inside which all trees will grow faster.

#### Describe alternatives you've considered.

None.

### Additional context

None.

**Comment by tastybento** [comment]
Currently, the radius is the island. Does it need to be more complex?

**Comment by BONNe** [comment]
I think it should be much simpler... without storing sapling location...
just a radius X around player when he twerks...

**Comment by tastybento** [comment]
Scanning blocks takes a lot of time. That would not be simpler.

**Comment by Poslovitch** [comment]
Basically, in modpacks it works within a 5 block radius, depending on the settings. I'm totally fine with the current implementation keeping track of all saplings on the islands, but it needs to check for the distance between the player's location and the sapling location.

**Comment by tastybento** [comment]
If the idea is to only have trees (or maybe in the future other plants) grow if you are close to them, then that's easy to do with a quick distancesquared vector check, but I actually designed it so that it would not do that and instead cover the whole island. I don't mind adding it as an option, I'm just saying I consciously decided not to do this type of limitation.

**Comment by tastybento** [comment]
Done.
